##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    - autoconf-archive
    - clang
    - gcc
    - git
    - make
    - startup-notification
    - which
    - glib2
    - gobject-introspection
    - gtk3
    - gtk-doc
    - mate-common
    - vala

  debian:
    # Useful URL: https://salsa.debian.org/debian-ayatana-team/ayatana-ido
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtest-dev
    - libgtk-3-dev
    - libx11-dev
    - libxi-dev
    - mate-common
    - valac

  fedora:
    - autoconf-archive
    - cairo-gobject-devel
    - clang-analyzer
    - clang
    - cppcheck-htmlreport
    - dconf-devel
    - desktop-file-utils
    - gcc
    - git
    - redhat-rpm-config
    - startup-notification-devel
    - glib2-devel
    - gobject-introspection-devel
    - gtest-devel
    - gtk-doc
    - gtk3-devel
    - libX11-devel
    - libXi-devel
    - make
    - mate-common
    - vala

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - git
    - gobject-introspection
    - gtk-doc-tools
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtest-dev
    - libgtk-3-dev
    - libx11-dev
    - libxi-dev
    - mate-common
    - valac

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare -Wunused-parameter"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --prefix=/usr --enable-gtk-doc --enable-compile-warnings=maximum
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     if [ ${DISTRO_NAME} == "fedora" ];then
  -         cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -         cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -         ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/${REPO_NAME}/raw/master/icons/16x16/apps/mate-desktop.png
  -     fi
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         make check
  -     fi
  -     make distcheck
  - fi
