# vim: set ts=2 sts=2 sw=2 expandtab :
dist: bionic
language: shell
os: linux
services:
  - docker

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

before_install:
  # let's use the MATE project's docker build scripts...
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - curl -Ls -o gen-index https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/gen-index.sh
  - sed -i gen-index -e "s/mate-desktop/ayatana-indicators/g"
  - chmod +x docker-build gen-index

install:
  - pip3 install PyGithub
  - ./docker-build --name ${DISTRO} --config .build.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .build.yml --build scripts --build autotools

env:
  - DISTRO="archlinux:latest"
  - DISTRO="debian:testing"
#  - DISTRO="fedora:latest"
  - DISTRO="ubuntu:rolling"
