# Use new bionic images, should yield newer compilers and packages
language: cpp
os: linux
dist: bionic

jobs:
  include:
    - name: "GCC 5.4"
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gobject-introspection
            - gtk-doc-tools
            - libgirepository1.0-dev
            - libglib2.0-dev
            - libgtest-dev
            - libgtk-3-dev
            - libx11-dev
            - libxi-dev
            - mate-common
            - valac

      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

    - name: "GCC 7.4"
      dist: bionic
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gobject-introspection
            - gtk-doc-tools
            - libgirepository1.0-dev
            - libglib2.0-dev
            - libgtest-dev
            - libgtk-3-dev
            - libx11-dev
            - libxi-dev
            - mate-common
            - valac

      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

    - name: "Clang 3.9"
      dist: xenial
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-xenial-3.9
          packages:
            - clang-3.9
            - gobject-introspection
            - gtk-doc-tools
            - libgirepository1.0-dev
            - libglib2.0-dev
            - libgtest-dev
            - libgtk-3-dev
            - libx11-dev
            - libxi-dev
            - mate-common
            - valac

      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"

    - name: "Clang 9.x"
      dist: bionic
      addons:
        apt:
          update: true
          sources:
            - llvm-toolchain-bionic-9
            - ubuntu-toolchain-r-test
          packages:
            - clang-9
            - gobject-introspection
            - gtk-doc-tools
            - libgirepository1.0-dev
            - libglib2.0-dev
            - libgtest-dev
            - libgtk-3-dev
            - libx11-dev
            - libxi-dev
            - mate-common
            - valac

      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"

before_install:
   - eval "${MATRIX_EVAL}"

before_scripts:
  - NOCONFIGURE=1 ./autogen.sh

script:
  - ./configure --disable-option-checking --disable-silent-rules --disable-maintainer-mode --disable-dependency-tracking
  - make && make check
